[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 