server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_api_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.example.secureapi: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  packages-to-scan: com.example.secureapi.controller 