server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${AIVEN_DATABASE_URL}
    username: ${AIVEN_DATABASE_USERNAME}
    password: ${AIVEN_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

logging:
  level:
    root: INFO
    com.example.secureapi: INFO
    org.hibernate.SQL: INFO
    com.zaxxer.hikari: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false 